// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zagstdvaupvzkxjmimog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZ3N0ZHZhdXB2emt4am1pbW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTkwNzcsImV4cCI6MjA2MTg3NTA3N30.h5sunnE1tXsoIoj96FCjQ_P3Q5bwvxiI93sjDX4cc_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);